volumes:
  pg_data:

services:
  journal-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5508:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
#  dnevnik.journal:
#    image: dnevnik.journal
#    build:
#      context: .
#      dockerfile: src/Dnevnik.Journal/Dockerfile
  
